# Database settings (Docker PostgreSQL on port 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/ticketrush_db
spring.datasource.username=ticketrush_user
spring.datasource.password=ticketrush_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis settings
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=ticketrush_mq_user
spring.rabbitmq.password=ticketrush_mq_password

# GraphQL path settings
spring.graphql.graphiql.enabled=true
spring.graphql.path=/graphql

# JWT Security Key Configuration
ticketrush.security.jwt.secret=9a6140ba934376378e9aa82a32cd93233bd82a20ea88ba6140ba934376378e9aa82a32cd93233bd82a20ea88ba6140ba934376378e9a
ticketrush.security.jwt.expiration=86400000
